### ISSUE TITLE
Meeting to organize the 3rd period

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-source-plone#119]
@cekk @ajayns @tisto 

We are end of the 2nd coding period.

We should have a hangout (could @cekk do the coordination) to plan the last period to have a documented release with enough features at the end of GSOC.

**Comment by cekk** [comment]
Sure, thanks for this reminder.
I think that the best moment is in our morning. At 9 like the weekly update?

What are good days for you? I'm unavailable only Wednesday.

**Comment by datakurre** [comment]
Already tomorrow? (Tuesday?)

**Comment by cekk** [comment]
Ok for me

**Comment by datakurre** [comment]
Ok, if @ajayns confirms that he could attend Hangout tomorrow 10th July at 9AM CET, let's have it and hope that also @tisto could attend. I recall @cekk has all our emails, so he could just call us? Otherwise @cekk could share the hangout link here a little before the time.

**Comment by cekk** [comment]
You should've received an appointment for tomorrow at 9AM (in the email there was a mistake).

The hangout link is in the email, but i paste it here anyway: https://meet.google.com/wdr-oodb-sbq

**Comment by ajayns** [comment]
Hey guys, sorry I couldn't confirm earlier, I was quite caught up.
And 9AM CET tomorrow would be fine by me, I've accepted the invitation that you've mailed!

**Comment by tisto** [comment]
Are we going to do the call? I am available.

Timo

**Comment by cekk** [comment]
Sorry Timo, it was at 9 and we started without you because we didn't had any feedback.

Btw: we are on schedule.
There are some things that we need to complete to finish the first version of the plugin and are listed in the to-do column of the project (the main things are collections and file/image handling I think).
In these weeks, if someone (I can, asko not)  could try the plugin with a real site and open issues for problems and missing documentations would be great.
After that, Ajay will work with the starter product and some documentation.

Am I missing something?

**Comment by ajayns** [comment]
Nope @cekk, you mentioned all the major things we had in our discussion. 
As you said primary goals right now is to handle collections and file/image handling, the goals are noted as issues in the GSoC project board. After this, @datakurre mentioned it'd be a good idea to work on gatsby-starter-plone along with narrative documentation (which would guide the user step by step or so like a tutorial) simultaneously and we're directly using plugin's features in the project.
