### ISSUE TITLE
Improvements : Majority of the source code resides in couple of files => Refactoring

### ISSUE THREAD

**Issue by pranshuchittora** [collective/gatsby-source-plone#166]
### Introduction
Hello, community
It's a good practice to write code in small modules(separate files) which are self-contained in itself. Which makes it easy to test, debug & maintain. 

The current source code of this project resides in a few files only, which contains hundreds of lines of code.
 
### Solution
Refactor the code into small modules(files) based of it's features.

1. Identify small features.
2. Isolate it.
3. Happy testing.

**Comment by datakurre** [comment]
Sure, but we also want to avoid premature optimization.

Good next step would probably to start refactoring in typescript and detect possible independent modules while doing that.

For example, utils.js contains only code that can be unit tested easily and it is mostly tested: 
https://coveralls.io/builds/21555274/source?filename=src/utils.js

**Comment by pranshuchittora** [comment]
@datakurre `premature optimisation`  ?
Pls elaborate.

**Comment by datakurre** [comment]
http://wiki.c2.com/?PrematureOptimization

I admit I used the term a bit out of its context (because this issue was not about performance, but maintainability).

I agree with the goal of this issue, but I'm not sure if an issue is a best way to do it. Instead I would prefer every pull request for actual features to make the code base a little bit better.

Would you have a tool or service to suggest that would do some static code analysis and score the code base for its complexity? Something coveralls does to tell us if a pull request increases or reduces code coverage.

**Comment by datakurre** [comment]
I consider this fixed by https://github.com/collective/gatsby-source-plone/pull/237
