### ISSUE TITLE
create the node when something added to PloneCMS

### ISSUE THREAD

**Issue by iFlameing** [collective/gatsby-source-plone#180]

**Comment by datakurre** [comment]
master branch now has a docker image with websocket notifications

I posted a brief gif animation showing it in action https://community.plone.org/t/gsoc-2019-gatsbyjs-preview-for-plone/8535/4

**Comment by iFlameing** [comment]
@datakurre I have created a pull request which is an initial commit. I created a node for the added field but Gatsby does not trigger the recompilation after the creation of node.
![Screenshot from 2019-06-06 00-39-40](https://user-images.githubusercontent.com/33936987/58983959-89ca8900-87f5-11e9-96b3-3781b1aaa8d2.png)

**Comment by datakurre** [comment]
@iFlameing FWIW Here's another plugin implementing "watchMode" similar to you are doing now https://github.com/sanity-io/gatsby-source-sanity

Remember that nodes are separate from pages. Adding node does not automatically add page (and I'm not sure how managing pages should be done properly, because they are created in the site project, not in plugin). But you should be able search for the new nodes in GatsbyJS GraphiQL console.

**Comment by datakurre** [comment]
Fixed in  #180.
