### ISSUE TITLE
Document pages not loading in docs gatsby-site

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-source-plone#52]
In the gatsby-site setup for documentation, links to individual pages of docs don't seem to be working, they seem to route to the 404 screen. 

https://collective.github.io/gatsby-source-plone/gatsby-source-plone/plugin_options
https://collective.github.io/gatsby-source-plone/gatsby-source-plone/search_traversal
https://collective.github.io/gatsby-source-plone/gatsby-source-plone/index

**Comment by datakurre** [comment]
@ajayns Yes. That's my fault. It works properly in development, but ``--prefix-paths`` build option double prefixed the index page.

Individual pages work fine:

https://collective.github.io/gatsby-source-plone/search_traversal/

I believe that the issue is that we have both ``./pages/index.js`` and then a page named ``index`` generated from the docs. So those overlap. I have plan to fix that so you can focus on the plugin.

(As you have noticed, I'm trying to learn to use Gatsby while you are using the plugin so that I can keep using it later when your GSOC is done :)

**Comment by ajayns** [comment]
Okay, that's cool! No issues.
Haha yes, I've noticed. That's nice! 

I see you've also used Bootstrap yes? The plan later was to add Semantic UI while working on the examples/use cases, but if you want to move forward like this I could modify the plans a bit.

**Comment by datakurre** [comment]
@ajayns Any particular reasons for Semantic UI?

I know that plone-react uses Semantic UI, but I don't see the direct connection from plone-react to this project.

Semantic UI is currently missing official SASS port. For me it has been looking like SASS has brighter future than LESS. I did try Semantic UI for some projects, but then I realized that and was unable to benefit from any of its "easy to theme" features, because of that.

**Comment by datakurre** [comment]
About the ``index`` issue. I need to finish my official workday at first, but I'm plan to drop the current ``/pages/index.js`` and let ``./docs/index.md`` to be the index. Possibly applying a special template for it.

**Comment by ajayns** [comment]
@datakurre Not really, in discussion with @tisto we went with that in the proposal just because, as you said, plone-react uses Semantic. And yes I agree, even I'ma fan of SASS, let's stick to Bootstrap then. 

And yes, that sounds good, do let me know if I can help on that in way.

**Comment by datakurre** [comment]
Ouch. I remember. I assumed that it is great because plone react uses it. I didn’t know then that SASS version is not official or documented :/ I am sorry for turning my coat on that.

**Comment by ajayns** [comment]
Haha, not an issue, Bootstrap is pretty simple to catch up on since I've used it already. Plus SASS support is pretty valuable, so yes.

**Comment by datakurre** [comment]
For now it seemed that's it is easier to keep using ``./pages/index.js`` for the index, but exclude index from docs from normal pages (but include its contents on that index page).

**Comment by ajayns** [comment]
Ok yes, that sounds like the best way to move on with this! @datakurre  Later maybe we can add a bit of styling so that it looks polished and users can understand clearly what we've done.

**Comment by datakurre** [comment]
I guessed wrong. Removing index did not remove double path prefixed. Needs to Google...

**Comment by datakurre** [comment]
@ajayns FYI. My mistake was to use relative paths with gatsby-link. Once I fixed them to absolute paths (starting with /), pathPrefix worked properly with gh-pages.

**Comment by ajayns** [comment]
@datakurre Oh alright, I have opened an issue in the Gatsby community about this plugin but yet to receive updates on it. https://github.com/gatsbyjs/gatsby/issues/5489
